server:
  port: 8085
spring:
  application:
    name: springstreamkafkaproducer
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
          zknodes: zookeeper:2181
      bindings:
         greetings-out:
            destination: greetingstopic
            content-type: application/json 
#greetings - kafka topic we use for both the inbound and outbound streams in our code. They both must use the same Kafka topic